paginate: 10
markdown: Kramdown
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
timezone: America/Chicago
encoding: UTF-8
permalink: posts/:year/:month/:title
title:
  zh: 夜阑卧听风吹雨
  en: Shi Yin's Blog
description:
  zh: 记录关于我所有的事情
  en: a blog about everything in my life
disqus_shortname: joysword
author:
  name:
    zh: 殷实
    en: Shi Yin
  github: joysword
  email: syin8@uic.edu
keywords:
  zh: joysword, 殷实, 个人主页, 博客, 作品集, 游戏, 电子游戏, Jekyll, Bootstrap, Font Awesome
  en: joysword, Shi Yin, Shi, Yin, personal website, portfolio, games, blog, Video Games, Jekyll, Bootstrap, Font Awesome
paginate_path: "page/:num"
analytics: UA-43448447-5
