plugins: [jekyll-paginate]
paginate: 6
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
timezone: America/Los_Angeles
encoding: UTF-8
permalink: posts/:year/:month/:title/
title:
  zh: 夜阑卧听风吹雨
  en: Shi Yin's Blog
description:
  zh: 记录关于我所有的事情
  en: a blog about everything in my life
disqus_shortname: joysword
author:
  name:
    zh: 殷实
    en: Shi Yin
  github: joysword
  email: joysword@me.com
keywords:
  zh: joysword, 殷实, 个人主页, 博客, 作品集, 游戏, 电子游戏, 虚拟现实, 数据可视化, 可视化, Jekyll, Bootstrap, Font Awesome
  en: joysword, Shi Yin, portfolio, games, blog, Video Games, Virtual Reality, Data Visualization, Jekyll, Bootstrap, Font Awesome
paginate_path: "page/:num"
analytics: UA-43448447-5
